### ISSUE TITLE
Cross Compiling Fails

### ISSUE THREAD

**Issue by joesixpack** [ResistancePlatform/resistance-core#74]
HOST=x86_64-w64-mingw32 ./resutil/build.sh -j$(nproc)

![image](https://user-images.githubusercontent.com/23145642/66556519-3e0e5000-eb05-11e9-958b-3a7613b1a357.png)

**Comment by solardiz** [comment]
This is related to issue #21. I think the issue shows up or disappears between compiler versions, and only on Windows so far. Unfortunately, the same fix we made for Dash isn't directly applicable for Resistance. I'll look into this issue and maybe come up with a workaround (e.g., on Windows on x86(-64) just assume the system is little-endian and skip the serialization).

**Comment by solardiz** [comment]
Upon a second look, these look like different instances of the same problem, where `memory_cleanse` is referred to by other parts of the tree, not the block header serialization I added. So we'll need a different workaround or fix, probably having to do with `memory_cleanse` itself.

**Comment by solardiz** [comment]
Relevant: https://github.com/zcash/zcash/pull/4482

**Comment by solardiz** [comment]
I've just made commit af1f9bdda7e762a3d95e48cd2b342e9c120be305 "Avoid dependency of memory_cleanse() on cleanse.o and OpenSSL", which should avoid at least the `memory_cleanse` issues seen here. I've only tested that it doesn't break build on/for Linux for me. I'd appreciate testing of builds for other platforms.

**Comment by joesixpack** [comment]
Still no joy.

[buildlog.txt](https://github.com/ResistancePlatform/resistance-core/files/4973055/buildlog.txt)

**Comment by solardiz** [comment]
@joesixpack Thank you for testing. The current understanding, due to testing by @whiteknightrader, is that parallel Windows builds fail (those with `-j`), whereas sequential ones succeed (without `-j`). Your `buildlog.txt` looks incomplete - perhaps there were errors in portions not included.

I think we're going to recommend that `-j` not be used when building for Windows.

**Comment by solardiz** [comment]
Updated `README.md` to recommend against `-j` when building for Windows. I'll close this issue, but it can be reopened if anyone feels like doing more on it.
